

import Head from "next/head";
import { Inter } from "next/font/google";
import ShoppingCart from "../molecules/shoppingCart/ShoppingCart";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Carrito de compras</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      
      <ShoppingCart />
   
      <style jsx global>{`
        body {
          font-family: ${inter}, sans-serif;
        }
      `}</style>
      </main>
    </>
  );
}