
import Head from 'next/head'
import { Inter } from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css'

import CardsSection from "@/organims/CardsSection";
import Carousel1 from '@/organims/Carousel1';
import ReviewCard from '@/organims/ReviewCard';
import ElegirnosSection from '@/organims/ElegirnosSection';
import BarilocheSection from '@/organims/BarilocheSection';


export default function Home() {
  return (
    <>
    <Head>
      <title>Proxpiriens</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="./LogoColorFloating.png" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" />
    </Head>
    
    <main>  
         
    <Carousel1 />
    <CardsSection/>
    <ElegirnosSection/>
    <ReviewCard/>
    <BarilocheSection/>
    
      
    </main>

    <style jsx global>{`

      main {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
      }

      body {
        font-family: 'Roboto', sans-serif;
      }

    `}</style>
  
  </>

)
};
